/*
 * weights.h
 * 
 * Exported weights for PatchClassifier6.
 * Generated by export_weights.py
 */

#ifndef WEIGHTS_H
#define WEIGHTS_H

// === Layer Dimensions ===
#define PATCH_H_IN 162
#define PATCH_W_IN 162
#define NUM_PATCHES 16

// Stem (1->16)
#define STEM_C_IN 1
#define STEM_C_OUT 16

// Layer 1 (16->32)
#define L1_C_IN 16
#define L1_C_MID 16
#define L1_C_OUT 32

// Layer 2 (32->64)
#define L2_C_IN 32
#define L2_C_MID 32
#define L2_C_OUT 64

// Layer 3 (64->128)
#define L3_C_IN 64
#define L3_C_MID 64
#define L3_C_OUT 128

// Layer 4 (128->256)
#define L4_C_IN 128
#define L4_C_MID 128
#define L4_C_OUT 256

// Layer 5 (256->256)
#define L5_C_IN 256
#define L5_C_MID 256
#define L5_C_OUT 256

// FC Layers
#define FC_PATCH_IN 256
#define FC_PATCH_OUT 32
#define FC_FINAL_IN 32
#define FC_FINAL_OUT 1

extern const float stem_conv_w[16][1][3][3];
extern const float stem_conv_b[16];
extern const float l1_dw_conv_w[16][1][3][3];
extern const float l1_dw_conv_b[16];
extern const float l1_pw_conv_w[32][16][1][1];
extern const float l1_pw_conv_b[32];
extern const float l2_dw_conv_w[32][1][3][3];
extern const float l2_dw_conv_b[32];
extern const float l2_pw_conv_w[64][32][1][1];
extern const float l2_pw_conv_b[64];
extern const float l3_dw_conv_w[64][1][3][3];
extern const float l3_dw_conv_b[64];
extern const float l3_pw_conv_w[128][64][1][1];
extern const float l3_pw_conv_b[128];
extern const float l4_dw_conv_w[128][1][3][3];
extern const float l4_dw_conv_b[128];
extern const float l4_pw_conv_w[256][128][1][1];
extern const float l4_pw_conv_b[256];
extern const float l5_dw_conv_w[256][1][3][3];
extern const float l5_dw_conv_b[256];
extern const float l5_pw_conv_w[256][256][1][1];
extern const float l5_pw_conv_b[256];
extern const float fc_patch_w[32][256];
extern const float fc_patch_b[32];
extern const float fc_final_w[1][32];
extern const float fc_final_b[1];

#endif // WEIGHTS_H
